import json
def results():
    # open json data to dict and return
    svm_dict = json.loads(svm_data)
    return svm_dict

svm_data = """[{"combination": "FY", "accuracy": 31}, {"combination": "PY", "accuracy": 44}, {"combination": "LN", "accuracy": 69}, {"combination": "PI", "accuracy": 30}, {"combination": "DI", "accuracy": 26}, {"combination": "MT", "accuracy": 32}, {"combination": "FY,PY", "accuracy": 44}, {"combination": "FY,LN", "accuracy": 48}, {"combination": "FY,PI", "accuracy": 57}, {"combination": "FY,DI", "accuracy": 48}, {"combination": "FY,MT", "accuracy": 59}, {"combination": "PY,LN", "accuracy": 69}, {"combination": "PY,PI", "accuracy": 67}, {"combination": "PY,DI", "accuracy": 45}, {"combination": "PY,MT", "accuracy": 62}, {"combination": "LN,PI", "accuracy": 47}, {"combination": "LN,DI", "accuracy": 67}, {"combination": "LN,MT", "accuracy": 45}, {"combination": "PI,DI", "accuracy": 62}, {"combination": "PI,MT", "accuracy": 62}, {"combination": "DI,MT", "accuracy": 64}, {"combination": "FY,PY,LN", "accuracy": 77}, {"combination": "FY,PY,PI", "accuracy": 79}, {"combination": "FY,PY,DI", "accuracy": 41}, {"combination": "FY,PY,MT", "accuracy": 44}, {"combination": "FY,LN,PI", "accuracy": 56}, {"combination": "FY,LN,DI", "accuracy": 79}, {"combination": "FY,LN,MT", "accuracy": 88}, {"combination": "FY,PI,DI", "accuracy": 56}, {"combination": "FY,PI,MT", "accuracy": 57}, {"combination": "FY,DI,MT", "accuracy": 60}, {"combination": "PY,LN,PI", "accuracy": 32}, {"combination": "PY,LN,DI", "accuracy": 52}, {"combination": "PY,LN,MT", "accuracy": 79}, {"combination": "PY,PI,DI", "accuracy": 51}, {"combination": "PY,PI,MT", "accuracy": 51}, {"combination": "PY,DI,MT", "accuracy": 52}, {"combination": "LN,PI,DI", "accuracy": 74}, {"combination": "LN,PI,MT", "accuracy": 66}, {"combination": "LN,DI,MT", "accuracy": 74}, {"combination": "PI,DI,MT", "accuracy": 73}, {"combination": "FY,PY,LN,PI", "accuracy": 48}, {"combination": "FY,PY,LN,DI", "accuracy": 81}, {"combination": "FY,PY,LN,MT", "accuracy": 59}, {"combination": "FY,PY,PI,DI", "accuracy": 51}, {"combination": "FY,PY,PI,MT", "accuracy": 51}, {"combination": "FY,PY,DI,MT", "accuracy": 57}, {"combination": "FY,LN,PI,DI", "accuracy": 85}, {"combination": "FY,LN,PI,MT", "accuracy": 66}, {"combination": "FY,LN,DI,MT", "accuracy": 72}, {"combination": "FY,PI,DI,MT", "accuracy": 67}, {"combination": "PY,LN,PI,DI", "accuracy": 71}, {"combination": "PY,LN,PI,MT", "accuracy": 72}, {"combination": "PY,LN,DI,MT", "accuracy": 72}, {"combination": "PY,PI,DI,MT", "accuracy": 54}, {"combination": "LN,PI,DI,MT", "accuracy": 75}, {"combination": "FY,PY,LN,PI,DI", "accuracy": 72}, {"combination": "FY,PY,LN,PI,MT", "accuracy": 68}, {"combination": "FY,PY,LN,DI,MT", "accuracy": 54}, {"combination": "FY,PY,PI,DI,MT", "accuracy": 57}, {"combination": "FY,LN,PI,DI,MT", "accuracy": 60}, {"combination": "PY,LN,PI,DI,MT", "accuracy": 73}
            ]"""

# print(results())