# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'part_data_file',
            },
        ),
    ]
