# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partdatafile',
            old_name='upload',
            new_name='uploaded',
        ),
    ]
