# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0003_auto_20171022_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdatafile',
            name='file',
            field=models.FileField(upload_to='static/csv'),
        ),
    ]
