# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0004_auto_20171022_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartFailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/csv/upload/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'part_fail_file',
            },
        ),
        migrations.AlterField(
            model_name='partdatafile',
            name='file',
            field=models.FileField(upload_to='static/csv/upload/'),
        ),
    ]
