# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 08:13
from __future__ import unicode_literals

import RawData.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RawData', '0007_auto_20171022_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partfailfile',
            name='file',
            field=models.FileField(upload_to=RawData.models.PartFailFile.content_file_name),
        ),
    ]
