# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='failure_type',
        ),
    ]
