# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0002_remove_record_failure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='failure_type',
            field=models.CharField(default='corrosion', max_length=255),
            preserve_default=False,
        ),
    ]
