# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0003_record_failure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='pipe',
        ),
        migrations.DeleteModel(
            name='Pipe',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
